---

- name: db servers
  hosts: dbservers
  become: yes

  tasks:
    - name: Install mariadb-server
      ansible.builtin.yum:
         name: mariadb-server
         state: present

    - name: Install pymysql   //Dependency to create a new database with a givin name
      ansible.builtin.yum:
         name: python3-PyMySQL
         state: present

    - name: Start Service
      ansible.builtin.service:
         name: mariadb
         state: started
         enabled: yes

    - name: Create a new database with name 'accounts'
      community.mysql. mysql_db:
         name: accounts
         state: present
         login_unix_socket: /var/lib/mysql/mysql.sock  //To allow ansible to connect to mysql server


    - name: Create database user with name 'admin' and password 'admin123' with all database privileges
       community.mysql.mysql_user:
         name: admin
         password: 'admin123'
         priv: '*.*:ALL'
         state: present
         login_unix_socket: /var/lib/mysql/mysql.sock